### ISSUE TITLE
having a problem with queries

### ISSUE THREAD

**Issue by dyyce** [almightycouch/rethinkdb_ecto#25]
Hey there,

first, thanks for the rethinkdb adapter for this repo. I tried another one, but it is not maintained anymore and it didn't work.
With this one I managed to set it up. 
The database is running and I created a simple Post CRUD

I am able to create new entries and list them. However, each time I try to query something(e.g. just to show the entry) using the ID, it gives me this error:

```
[debug] ** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:295: value `"a9f055fb-b5d4-475d-aadd-db9f4226f494"` in `where` cannot be cast to type :id in query:

from p in Twitchsap.Post,
  where: p.id == ^"a9f055fb-b5d4-475d-aadd-db9f4226f494",
  select: p

    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:64: Ecto.Repo.Queryable.one/4
    (twitchsap) web/controllers/post_controller.ex:30: Twitchsap.PostController.show/2
    (twitchsap) web/controllers/post_controller.ex:1: Twitchsap.PostController.action/2
    (twitchsap) web/controllers/post_controller.ex:1: Twitchsap.PostController.phoenix_controller_pipeline/2
    (twitchsap) lib/twitchsap/endpoint.ex:1: Twitchsap.Endpoint.instrument/4
    (twitchsap) lib/phoenix/router.ex:261: Twitchsap.Router.dispatch/2
```

the function looks like this:
```
def show(conn, %{"id" => id}) do
    post = Repo.get(Post, id)
    render(conn, "show.html", post: post)
  end
```

**Comment by cohawk** [comment]
At a quick glance - I believe you need to set your model's :id type to :binary_id.

Easiest way is in your web.ex model definition:

```elixir
def model do
    quote do
      use Ecto.Schema

      @primary_key {:id, :binary_id, autogenerate: false}
      @foreign_key_type  :binary_id

      import Ecto
      import Ecto.Changeset
      import Ecto.Query, only: [from: 1, from: 2]
    end
  end
```

**Comment by dyyce** [comment]
that was it. Thx!!!
