### ISSUE TITLE
Difficulty actually starting with this project...

### ISSUE THREAD

**Issue by jdvs1** [almightycouch/rethinkdb_ecto#31]
I am having difficulty getting started with the adapter. I was following instructions and got up to the `mix ecto.create` command. Here's the error when running that:

```
** (ArgumentError) adapter Ecto.Adapters.RethinkDB was not compiled, ensure it is correct and it is included as a project dependency
```

The `mix.exs` file:

```
defmodule MyApi.Mixfile do
  use Mix.Project

  def project do
    [app: :my_api,
     version: "0.0.1",
     elixir: "~> 1.2",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {MyApi, []},
     applications: [
      :cowboy,
      :ecto,
      :gettext,
      :logger,
      :phoenix,
      :phoenix_html,
      :phoenix_pubsub,
      :rethinkdb_ecto
    ]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
     {:cowboy, "~> 1.0"},
     {:ecto, "~> 2.1"},
     {:rethinkdb_ecto, "~> 0.6"},
     {:gettext, "~> 0.11"},
     {:phoenix, "~> 1.2.1"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:phoenix_pubsub, "~> 1.0"}
    ]
  end
end
```

The `config/config.exs` file:

```
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.
use Mix.Config

config :my_api, MyApi.Repo,
  adapter: Ecto.Adapters.RethinkDB,
  database: "my_api_repo",
  username: "user",
  password: "pass",
  hostname: "localhost"


config :my_api,
ecto_repos: [MyApi.Repo]

# Configures the endpoint
config :my_api, MyApi.Endpoint,
  adapter: RethinkDB.Ecto,
  url: [host: "localhost"],
  secret_key_base: "dBDaxMWN33JmWDEMiYA5hJ7ZjdwOwD2nYbJe8CFrjsCkpCoGAx4VDRVUOzqRsJ2X",
  render_errors: [view: MyApi.ErrorView, accepts: ~w(html json)]
  # pubsub: [name: MyApi.PubSub,
  #          adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"
```

The `web/models/user.ex` file:
```
defmodule User do
  use Ecto.Schema

  # You must define your primary-key and foreign-key types as :binary_id
  @primary_key {:id, :binary_id, autogenerate: false}
  @foreign_key_type :binary_id

  schema "users" do
    field :about, :string
    field :bio, :string
    field :email, :string
    field :name, :string
    timestamps
  end
end
```

Any ideas why?

Is there an example of using this adapter somewhere, so that I may look and compare?

**Comment by cohawk** [comment]
The error says the adapter dependency was not compiled.  You need to run `mix deps.compile`

**Comment by jdvs1** [comment]
@cohawk  still getting the same error:

```
$ mix deps.compile
==> fs (compile)
==> ranch (compile)
==> poolboy (compile)
==> cowlib (compile)
==> cowboy (compile)

$ mix ecto.create
Compiling 13 files (.ex)

== Compilation error on file lib/my_api/repo.ex ==
** (ArgumentError) adapter Ecto.Adapters.RethinkDB was not compiled, ensure it is correct and it is included as a project dependency
    lib/ecto/repo/supervisor.ex:55: Ecto.Repo.Supervisor.compile_config/2
    lib/my_api/repo.ex:2: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

```

**Comment by cohawk** [comment]
first run `mix deps.get` to fetch your dependancies, then run 'mix deps.compile'

**Comment by jdvs1** [comment]
@cohawk Thanks for taking the time to help. Do you happen to know of anything else I might be able to try?

```
$ mix deps.get
Running dependency resolution...
All dependencies up to date

$ mix deps.compile
==> fs (compile)
==> ranch (compile)
==> poolboy (compile)
==> cowlib (compile)
==> cowboy (compile)

$ mix ecto.create
Compiling 13 files (.ex)

== Compilation error on file lib/my_api/repo.ex ==
** (ArgumentError) adapter Ecto.Adapters.RethinkDB was not compiled, ensure it is correct and it is included as a project dependency
    lib/ecto/repo/supervisor.ex:55: Ecto.Repo.Supervisor.compile_config/2
    lib/my_api/repo.ex:2: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by jdvs1** [comment]
@cohawk would you be willing to paste an example repo to show how you can use this, something simple up to the point of the querying for an item?

**Comment by cohawk** [comment]
@jdvs1 I actually have been trying to setup an example for the past hour, and running into different dependency errors.  Once I finally got things to compile I am seeing the same error, so its not entirely something you are doing incorrectly.  I think it may be related to Phoenix v1.2.1 at the moment - Standby while I am doing some troubleshooting.

**Comment by cohawk** [comment]
I really went down a rabbit-hole there troubleshooting a Phoenix Live Reload issue with Elrang :fs v2.12.0.

Anyways @jdvs1 - thats not your issue.  Your issue is with your `config/config.exs`:

Under MyApi.Endpoint:

`config :my_api, MyApi.Endpoint,
  adapter: RethinkDB.Ecto,
...`

delete the `adapter: RethinkDB.Ecto` line.  Your Endpoints are not using the RethinkDB Ecto Adapter, only your DB Repo is.

Under MyApi.Repo:

`config :my_api, MyApi.Repo,
  adapter: Ecto.Adapters.RethinkDB,
...`

the adapter name is incorrect, which is why you get the compilation error that it cannot find the adapter.  You had the correct adapter name under MyApi.Endpoint (just in the wrong place).

`# Configure your database
config :my_api, MyApi.Repo,
  adapter: RethinkDB.Ecto,
  database: "my_api_repo",
  username: "user",
  password: "pass",
  hostname: "localhost"`

That should at least fix your compilation error, but you might still have some config issue with mix.exs including ecto directly as a dependency instead of phoenix_ecto, etc

Ill create and upload a quick working example repo if you still need.

**Comment by jdvs1** [comment]
@cohawk That fixed the compilation errors, thank you!
