### ISSUE TITLE
Adapter not working with Ecto 2.2.x

### ISSUE THREAD

**Issue by FrancisMurillo** [almightycouch/rethinkdb_ecto#41]
Hello,

I followed the directions in setting up an `Api.Repo`. Everytime I use `Api.Repo.all(Api.Tick)`, I get the following error

```
** (KeyError) key :fields not found in: %{prefix: nil, preloads: [], select: %{assocs: [], postprocess: {:from, :any, {:source, :from}}, preprocess: [{:source, {"ticks", Api.Tick}, [id: :binary_id, buy: :decimal, sell: :decimal, inserted_at: :naive_datetime, updated_at: :naive_datetime]}], take: []}, sources: {{"ticks", Api.Tick}}}
    (rethinkdb_ecto) lib/rethinkdb_ecto.ex:162: RethinkDB.Ecto.execute/6
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

Any idea how to resolve this would be great.

**Comment by redrabbit** [comment]
Can you give the version of Ecto you are using.

**Comment by FrancisMurillo** [comment]
@redrabbit My ecto version is `2.2.6`.

**Comment by redrabbit** [comment]
Some changes between Ecto 2.1.x and 2.2.x break things for the RethinkDB adapter. I'm investigating this. Meanwhile, you could use Ecto 2.1.

**Comment by renews** [comment]
Any news on this?

**Comment by redrabbit** [comment]
@renews, I did not find time to come with a fix for this. I will try once I have a little spare time. Any kind of help (investigations, code-review, PRs) is very welcome.
